// <auto-generated />
using System;
using Levi9.ERP.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi9.ERP.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230521201253_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PriceListId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Test1 Address 123",
                            Email = "test1@example.com",
                            GlobalId = new Guid("b8c03b21-adf0-4148-80ac-8852907419b7"),
                            LastUpdate = "133291695156186842",
                            Name = "Test1 Client",
                            Password = "mL+yK0IZ6Tbe5ZgQVme2GWD8ayRg9VtRI897U0LuB0w=",
                            Phone = "0611234567",
                            PriceListId = 1,
                            Salt = "ypt+7c/LVq46Eg=="
                        },
                        new
                        {
                            Id = 2,
                            Address = "Test2 Address 123",
                            Email = "test2@example.com",
                            GlobalId = new Guid("1e3b3042-4123-4610-8bb6-51b1282dc768"),
                            LastUpdate = "133291695252052729",
                            Name = "Test2 Client",
                            Password = "MWpg/GsSmNKsvjH0ApaCvOG4C/G4sJb58hudQeRxzEc=",
                            Phone = "0621234567",
                            PriceListId = 2,
                            Salt = "aTgpP/3Uf1JULg=="
                        },
                        new
                        {
                            Id = 3,
                            Address = "Test3 Address 123",
                            Email = "test3@example.com",
                            GlobalId = new Guid("5c69a8f5-8eb2-4d89-b21f-7e5e3aa00c08"),
                            LastUpdate = "133291695380809913",
                            Name = "Test3 Client",
                            Password = "uOEE7w8xH/lX2mmKdgb63SxqItyMrLfamMbYx5uSn7Y=",
                            Phone = "0631234567",
                            PriceListId = 3,
                            Salt = "boAfkuX2rmOaaA=="
                        },
                        new
                        {
                            Id = 4,
                            Address = "Test4 Address 123",
                            Email = "test4@example.com",
                            GlobalId = new Guid("d3d4e623-e6bc-44e4-98cb-681ef30b1fd4"),
                            LastUpdate = "133291695478630236",
                            Name = "Test4 Client",
                            Password = "Zr9Dm1X54LUOAqAybdKj+96MS98kLfrk7dUSB2kXn6s=",
                            Phone = "0641234567",
                            PriceListId = 4,
                            Salt = "ATpzta8FakmUvA=="
                        },
                        new
                        {
                            Id = 5,
                            Address = "Test5 Address 123",
                            Email = "test5@example.com",
                            GlobalId = new Guid("4da162c6-1af1-422e-be9c-debec2c62b54"),
                            LastUpdate = "133291695569534051",
                            Name = "Test5 Client",
                            Password = "PylZhPreW4GCLJ5zPs19QaVFqH+clUKonOGy+R3s+X8=",
                            Phone = "0651234567",
                            PriceListId = 5,
                            Salt = "r6H61KFl8j041w=="
                        },
                        new
                        {
                            Id = 6,
                            Address = "Test6 Address 123",
                            Email = "test6@example.com",
                            GlobalId = new Guid("e4d4fc68-0fa9-4356-b68f-886342655080"),
                            LastUpdate = "133291695663444894",
                            Name = "Test6 Client",
                            Password = "kgrSYNIZgqg2NKyxe2xBgmiKmQBp/cUiprmFuxyqCnk=",
                            Phone = "0661234567",
                            PriceListId = 6,
                            Salt = "QX8u19aR8y3QmQ=="
                        },
                        new
                        {
                            Id = 7,
                            Address = "Test7 Address 123",
                            Email = "test7@example.com",
                            GlobalId = new Guid("4470cd66-a960-4abc-ab54-45d92a700e80"),
                            LastUpdate = "133291695757736110",
                            Name = "Test7 Client",
                            Password = "uN1+O4ywbrGcKAVjKCXfCILz8K57UW+0fLzz/G+pMOg=",
                            Phone = "0671234567",
                            PriceListId = 7,
                            Salt = "qWurv2IcifFGJQ=="
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DocumentType = "INVOICE",
                            GlobalId = new Guid("494ad822-8ee2-47c3-938f-2de7a43db41a"),
                            LastUpdate = "634792557112051692"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Price", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<float>("PriceValue")
                        .HasColumnType("real");

                    b.HasKey("ProductId", "PriceListId");

                    b.HasIndex("PriceListId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956083",
                            PriceValue = 9750.25f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956098",
                            PriceValue = 82.88f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956109",
                            PriceValue = 70.2f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956175",
                            PriceValue = 94.58f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956188",
                            PriceValue = 607.44f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956200",
                            PriceValue = 6922.68f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956211",
                            PriceValue = 10237.76f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956222",
                            PriceValue = 4121.5f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956233",
                            PriceValue = 35.03f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956244",
                            PriceValue = 29.67f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956255",
                            PriceValue = 39.98f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956265",
                            PriceValue = 256.77f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956275",
                            PriceValue = 2926.26f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956286",
                            PriceValue = 4327.57f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956296",
                            PriceValue = 6383.75f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956307",
                            PriceValue = 54.26f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956317",
                            PriceValue = 45.96f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956328",
                            PriceValue = 61.92f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956339",
                            PriceValue = 397.71f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956349",
                            PriceValue = 4532.46f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956359",
                            PriceValue = 6702.94f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956417",
                            PriceValue = 8925f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956428",
                            PriceValue = 75.86f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956484",
                            PriceValue = 64.26f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956497",
                            PriceValue = 86.57f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956507",
                            PriceValue = 556.03f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956517",
                            PriceValue = 6336.75f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956528",
                            PriceValue = 9371.25f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956538",
                            PriceValue = 5241f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956549",
                            PriceValue = 44.55f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956559",
                            PriceValue = 37.74f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956570",
                            PriceValue = 50.84f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956580",
                            PriceValue = 326.51f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956592",
                            PriceValue = 3721.11f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956602",
                            PriceValue = 5503.05f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956612",
                            PriceValue = 7568.5f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956623",
                            PriceValue = 64.33f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956633",
                            PriceValue = 54.49f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956643",
                            PriceValue = 73.41f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956654",
                            PriceValue = 471.52f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956664",
                            PriceValue = 5373.63f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956675",
                            PriceValue = 7946.92f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956685",
                            PriceValue = 1953.75f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956695",
                            PriceValue = 16.61f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956752",
                            PriceValue = 14.07f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956764",
                            PriceValue = 18.95f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956775",
                            PriceValue = 121.72f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956786",
                            PriceValue = 1387.16f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956796",
                            PriceValue = 2051.44f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956807",
                            PriceValue = 6546.5f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956818",
                            PriceValue = 55.65f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956828",
                            PriceValue = 47.13f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956839",
                            PriceValue = 63.5f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956849",
                            PriceValue = 407.85f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956860",
                            PriceValue = 4648.01f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956870",
                            PriceValue = 6873.82f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956880",
                            PriceValue = 4037f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956891",
                            PriceValue = 34.31f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956901",
                            PriceValue = 29.07f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956912",
                            PriceValue = 39.16f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956922",
                            PriceValue = 251.51f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956933",
                            PriceValue = 2866.27f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956943",
                            PriceValue = 4238.85f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956954",
                            PriceValue = 8614.5f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735956964",
                            PriceValue = 73.22f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957009",
                            PriceValue = 62.02f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957020",
                            PriceValue = 83.56f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957031",
                            PriceValue = 536.68f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957042",
                            PriceValue = 6116.29f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957052",
                            PriceValue = 9045.22f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957063",
                            PriceValue = 1386.5f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957073",
                            PriceValue = 11.79f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957084",
                            PriceValue = 9.98f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957094",
                            PriceValue = 13.45f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957105",
                            PriceValue = 86.38f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957115",
                            PriceValue = 984.41f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957126",
                            PriceValue = 1455.82f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957136",
                            PriceValue = 5970.5f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957146",
                            PriceValue = 50.75f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957157",
                            PriceValue = 42.99f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957167",
                            PriceValue = 57.91f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957178",
                            PriceValue = 371.96f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957188",
                            PriceValue = 4239.05f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957198",
                            PriceValue = 6269.02f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957209",
                            PriceValue = 3177.25f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957219",
                            PriceValue = 27.01f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957266",
                            PriceValue = 22.88f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957277",
                            PriceValue = 30.82f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957287",
                            PriceValue = 197.94f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957298",
                            PriceValue = 2255.85f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957308",
                            PriceValue = 3336.11f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957318",
                            PriceValue = 9264.75f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957329",
                            PriceValue = 78.75f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957339",
                            PriceValue = 66.71f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957349",
                            PriceValue = 89.87f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957360",
                            PriceValue = 577.19f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957371",
                            PriceValue = 6577.97f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957381",
                            PriceValue = 9727.99f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957391",
                            PriceValue = 7812f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957402",
                            PriceValue = 66.4f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957412",
                            PriceValue = 56.25f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957422",
                            PriceValue = 75.78f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957433",
                            PriceValue = 486.69f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957443",
                            PriceValue = 5546.52f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957454",
                            PriceValue = 8202.6f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957464",
                            PriceValue = 2985.25f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957474",
                            PriceValue = 25.37f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957485",
                            PriceValue = 21.49f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957529",
                            PriceValue = 28.96f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957540",
                            PriceValue = 185.98f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957551",
                            PriceValue = 2119.53f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdate = "133291735735957561",
                            PriceValue = 3134.51f
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a43db411"),
                            LastUpdate = "634792557112051690",
                            Name = "RSD Price List"
                        },
                        new
                        {
                            Id = 2,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a13db412"),
                            LastUpdate = "634792557112051691",
                            Name = "EUR Price List"
                        },
                        new
                        {
                            Id = 3,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db413"),
                            LastUpdate = "634792557112051692",
                            Name = "GBP Price List"
                        },
                        new
                        {
                            Id = 4,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a43db414"),
                            LastUpdate = "634792557112051693",
                            Name = "USD Price List"
                        },
                        new
                        {
                            Id = 5,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a13db415"),
                            LastUpdate = "634792557112051694",
                            Name = "RMB Price List"
                        },
                        new
                        {
                            Id = 6,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db416"),
                            LastUpdate = "634792557112051695",
                            Name = "INR Price List"
                        },
                        new
                        {
                            Id = 7,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db41a"),
                            LastUpdate = "634792557112051696",
                            Name = "JPY Price List"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 104,
                            GlobalId = new Guid("6f68f25e-9645-4da9-b66f-8edbebb8a6e7"),
                            ImageUrl = "images/tshirtimage/T-ShirtBlack.png",
                            LastUpdate = "133291735735955816",
                            Name = "T-ShirtBlack"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 138,
                            GlobalId = new Guid("d68bce12-9f03-4e5f-b0b9-3ad1205afda4"),
                            ImageUrl = "images/tshirtimage/T-ShirtBlue.png",
                            LastUpdate = "133291735735955883",
                            Name = "T-ShirtBlue"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 745,
                            GlobalId = new Guid("2c103912-7b0f-4469-8769-3989a4d62bc2"),
                            ImageUrl = "images/tshirtimage/T-ShirtBrown.png",
                            LastUpdate = "133291735735955893",
                            Name = "T-ShirtBrown"
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 5,
                            GlobalId = new Guid("a6c74b0b-b1f3-4e12-b6d2-6c38a3903ce6"),
                            ImageUrl = "images/tshirtimage/T-ShirtGreen.png",
                            LastUpdate = "133291735735955904",
                            Name = "T-ShirtGreen"
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 57,
                            GlobalId = new Guid("8dbff2d4-42a0-4fe7-9864-05571f3c22db"),
                            ImageUrl = "images/tshirtimage/T-ShirtPurple.png",
                            LastUpdate = "133291735735955914",
                            Name = "T-ShirtPurple"
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 224,
                            GlobalId = new Guid("9f7c8b37-0e37-49ed-af1f-4e6a7428a873"),
                            ImageUrl = "images/tshirtimage/T-ShirtRed.png",
                            LastUpdate = "133291735735955925",
                            Name = "T-ShirtRed"
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 150,
                            GlobalId = new Guid("e0a01813-5f43-4a15-934f-9946ef8f4182"),
                            ImageUrl = "images/tshirtimage/T-ShirtRose.png",
                            LastUpdate = "133291735735955935",
                            Name = "T-ShirtRose"
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 186,
                            GlobalId = new Guid("156fd903-9fd2-41af-9b09-600d598b31c4"),
                            ImageUrl = "images/tshirtimage/T-ShirtYellow.png",
                            LastUpdate = "133291735735955945",
                            Name = "T-ShirtYellow"
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 104,
                            GlobalId = new Guid("6f8799a7-097b-45f4-a8f0-805784ee24a6"),
                            ImageUrl = "images/tshirtimage/T-ShirtBlack9gradient.png",
                            LastUpdate = "133291735735955956",
                            Name = "T-ShirtBlack 9 Gradient"
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 138,
                            GlobalId = new Guid("49674251-6b45-437f-8c7a-34a0b1a34c01"),
                            ImageUrl = "images/tshirtimage/T-ShirtBlue9gradient.png",
                            LastUpdate = "133291735735955967",
                            Name = "T-ShirtBlue 9 Gradient"
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 745,
                            GlobalId = new Guid("7b5ae8b9-12a0-4a19-9c37-943bc4cc5a3e"),
                            ImageUrl = "images/tshirtimage/T-ShirtBrown9gradient.png",
                            LastUpdate = "133291735735955978",
                            Name = "T-ShirtBrown 9 Gradient"
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 5,
                            GlobalId = new Guid("097dbb41-2aa0-4fbf-8986-bdf8e4e0d4b9"),
                            ImageUrl = "images/tshirtimage/T-ShirtGreen9gradient.png",
                            LastUpdate = "133291735735955988",
                            Name = "T-ShirtGreen 9 Gradient"
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 57,
                            GlobalId = new Guid("5f8d15b2-4c4d-4e7a-8902-d78d3b4cb10b"),
                            ImageUrl = "images/tshirtimage/T-ShirtPurple9gradient.png",
                            LastUpdate = "133291735735955998",
                            Name = "T-ShirtPurple 9 Gradient"
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 224,
                            GlobalId = new Guid("4d50363a-2dc4-4ef0-8bde-682758f0f801"),
                            ImageUrl = "images/tshirtimage/T-ShirtRed9gradient.png",
                            LastUpdate = "133291735735956007",
                            Name = "T-ShirtRed 9 Gradient"
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 150,
                            GlobalId = new Guid("1835ee0e-3275-4ff9-9d79-1a2e3b5e15e3"),
                            ImageUrl = "images/tshirtimage/T-ShirtRose9gradient.png",
                            LastUpdate = "133291735735956018",
                            Name = "T-ShirtRose 9 Gradient"
                        },
                        new
                        {
                            Id = 16,
                            AvailableQuantity = 186,
                            GlobalId = new Guid("e5e4a551-2b64-43fc-86e1-4c1c0f6880fe"),
                            ImageUrl = "images/tshirtimage/T-ShirtYellow9gradient.png",
                            LastUpdate = "133291735735956027",
                            Name = "T-ShirtYellow 9 Gradient"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.ProductDocument", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<float>("PriceValue")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ProductDocuments");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DocumentId = 1,
                            Currency = "USD",
                            PriceValue = 12f,
                            Quantity = 11
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Client", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Price", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.PriceList", "PriceList")
                        .WithMany("Prices")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.ERP.Domain.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.ProductDocument", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.Document", "Document")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.ERP.Domain.Models.Product", "Product")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.Navigation("ProductDocuments");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.PriceList", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
