// <auto-generated />
using System;
using Levi9.ERP.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi9.ERP.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PriceListId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Test1 Address 123",
                            Email = "test1@example.com",
                            GlobalId = new Guid("b8c03b21-adf0-4148-80ac-8852907419b7"),
                            LastUpdate = "111111111111111111",
                            Name = "Test1 Client",
                            Password = "mL+yK0IZ6Tbe5ZgQVme2GWD8ayRg9VtRI897U0LuB0w=",
                            Phone = "0611234567",
                            PriceListId = 1,
                            Salt = "ypt+7c/LVq46Eg=="
                        },
                        new
                        {
                            Id = 2,
                            Address = "Test2 Address 123",
                            Email = "test2@example.com",
                            GlobalId = new Guid("1e3b3042-4123-4610-8bb6-51b1282dc768"),
                            LastUpdate = "111111111111111111",
                            Name = "Test2 Client",
                            Password = "MWpg/GsSmNKsvjH0ApaCvOG4C/G4sJb58hudQeRxzEc=",
                            Phone = "0621234567",
                            PriceListId = 2,
                            Salt = "aTgpP/3Uf1JULg=="
                        },
                        new
                        {
                            Id = 3,
                            Address = "Test3 Address 123",
                            Email = "test3@example.com",
                            GlobalId = new Guid("5c69a8f5-8eb2-4d89-b21f-7e5e3aa00c08"),
                            LastUpdate = "111111111111111111",
                            Name = "Test3 Client",
                            Password = "uOEE7w8xH/lX2mmKdgb63SxqItyMrLfamMbYx5uSn7Y=",
                            Phone = "0631234567",
                            PriceListId = 3,
                            Salt = "boAfkuX2rmOaaA=="
                        },
                        new
                        {
                            Id = 4,
                            Address = "Test4 Address 123",
                            Email = "test4@example.com",
                            GlobalId = new Guid("d3d4e623-e6bc-44e4-98cb-681ef30b1fd4"),
                            LastUpdate = "111111111111111111",
                            Name = "Test4 Client",
                            Password = "Zr9Dm1X54LUOAqAybdKj+96MS98kLfrk7dUSB2kXn6s=",
                            Phone = "0641234567",
                            PriceListId = 4,
                            Salt = "ATpzta8FakmUvA=="
                        },
                        new
                        {
                            Id = 5,
                            Address = "Test5 Address 123",
                            Email = "test5@example.com",
                            GlobalId = new Guid("4da162c6-1af1-422e-be9c-debec2c62b54"),
                            LastUpdate = "111111111111111111",
                            Name = "Test5 Client",
                            Password = "PylZhPreW4GCLJ5zPs19QaVFqH+clUKonOGy+R3s+X8=",
                            Phone = "0651234567",
                            PriceListId = 5,
                            Salt = "r6H61KFl8j041w=="
                        },
                        new
                        {
                            Id = 6,
                            Address = "Test6 Address 123",
                            Email = "test6@example.com",
                            GlobalId = new Guid("e4d4fc68-0fa9-4356-b68f-886342655080"),
                            LastUpdate = "111111111111111111",
                            Name = "Test6 Client",
                            Password = "kgrSYNIZgqg2NKyxe2xBgmiKmQBp/cUiprmFuxyqCnk=",
                            Phone = "0661234567",
                            PriceListId = 6,
                            Salt = "QX8u19aR8y3QmQ=="
                        },
                        new
                        {
                            Id = 7,
                            Address = "Test7 Address 123",
                            Email = "test7@example.com",
                            GlobalId = new Guid("4470cd66-a960-4abc-ab54-45d92a700e80"),
                            LastUpdate = "111111111111111111",
                            Name = "Test7 Client",
                            Password = "uN1+O4ywbrGcKAVjKCXfCILz8K57UW+0fLzz/G+pMOg=",
                            Phone = "0671234567",
                            PriceListId = 7,
                            Salt = "qWurv2IcifFGJQ=="
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DocumentType = "INVOICE",
                            GlobalId = new Guid("494ad822-8ee2-47c3-938f-2de7a43db41a"),
                            LastUpdate = "634792557112051692"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Price", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<float>("PriceValue")
                        .HasColumnType("real");

                    b.HasKey("ProductId", "PriceListId");

                    b.HasIndex("PriceListId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("f7b145a2-1b70-4384-b747-5dd88ed7e735"),
                            LastUpdate = "133295606978041387",
                            PriceValue = 9750.25f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("752e4749-d1d6-4ecc-97eb-911d5e346782"),
                            LastUpdate = "133295606978041491",
                            PriceValue = 82.88f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("6c4bb723-30ca-43ca-bcf8-aaef7379b877"),
                            LastUpdate = "133295606978041512",
                            PriceValue = 70.2f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("d23b1cd4-802d-4f9e-befc-e0ec7e1ba7b8"),
                            LastUpdate = "133295606978041531",
                            PriceValue = 94.58f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("9f7d8f0a-9878-4b5e-b20f-68a8b9f45b06"),
                            LastUpdate = "133295606978041548",
                            PriceValue = 607.44f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("11a8dd97-c5b9-462e-a24b-f38b3706baf1"),
                            LastUpdate = "133295606978041568",
                            PriceValue = 6922.68f
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("fae86c15-bd88-4247-b1d1-366832031eb2"),
                            LastUpdate = "133295606978041601",
                            PriceValue = 10237.76f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("72540990-e38f-43b9-83f8-e37d9266e57b"),
                            LastUpdate = "133295606978041620",
                            PriceValue = 4121.5f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("6af6d230-1f71-419a-9656-115dbe33431e"),
                            LastUpdate = "133295606978041637",
                            PriceValue = 35.03f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("40144a0d-ebdf-46d6-bc43-350d1f0eea86"),
                            LastUpdate = "133295606978041657",
                            PriceValue = 29.67f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("6e2d1fb5-051a-4c20-b7ef-da50d5a889b3"),
                            LastUpdate = "133295606978041674",
                            PriceValue = 39.98f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("7232adc2-91be-4b95-9971-143228c16657"),
                            LastUpdate = "133295606978041691",
                            PriceValue = 256.77f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("6bd10c85-8ceb-4549-80c5-6f78fd6be054"),
                            LastUpdate = "133295606978041744",
                            PriceValue = 2926.26f
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("7face104-8068-4227-9e3f-b0616bb33166"),
                            LastUpdate = "133295606978041764",
                            PriceValue = 4327.57f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("b15f994f-2379-4193-995e-697524808aeb"),
                            LastUpdate = "133295606978041784",
                            PriceValue = 6383.75f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("160fbd02-027c-45a9-8195-7ccc8a6fbcd7"),
                            LastUpdate = "133295606978041800",
                            PriceValue = 54.26f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("1b741325-c66e-4b60-bee5-5f9d6b584665"),
                            LastUpdate = "133295606978041817",
                            PriceValue = 45.96f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("aad1fa94-5615-4591-ac2d-8519f8ef6798"),
                            LastUpdate = "133295606978041836",
                            PriceValue = 61.92f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("60c67ff3-536e-4fb7-a469-474156562e3a"),
                            LastUpdate = "133295606978041853",
                            PriceValue = 397.71f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("f32c7bb6-f0c7-4f14-9e93-88060f872081"),
                            LastUpdate = "133295606978041869",
                            PriceValue = 4532.46f
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("f9a84799-ca11-4e54-adaa-825299012dbb"),
                            LastUpdate = "133295606978041886",
                            PriceValue = 6702.94f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("c951aeb5-8589-4028-aa11-b0d3973e28a9"),
                            LastUpdate = "133295606978041902",
                            PriceValue = 8925f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("356926c3-beb9-44e5-a253-82846699a279"),
                            LastUpdate = "133295606978041921",
                            PriceValue = 75.86f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("e714102e-2eb2-4509-b945-e8670085f852"),
                            LastUpdate = "133295606978041937",
                            PriceValue = 64.26f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("5fec5b05-a84d-4e8d-ae1b-f4141baad088"),
                            LastUpdate = "133295606978041953",
                            PriceValue = 86.57f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("f9d269ce-577e-4bb4-85ee-1e4b3840438d"),
                            LastUpdate = "133295606978041970",
                            PriceValue = 556.03f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("b2341e2a-63a7-42b0-8649-c9de20be0e79"),
                            LastUpdate = "133295606978041986",
                            PriceValue = 6336.75f
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("caf3fde0-1274-4dae-83d5-ef364cefb1e5"),
                            LastUpdate = "133295606978042002",
                            PriceValue = 9371.25f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("e6f40e6f-fbcd-4498-ba88-65f28abad478"),
                            LastUpdate = "133295606978042019",
                            PriceValue = 5241f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("6c3e25b2-33c5-4479-bed5-41717a2fdfb0"),
                            LastUpdate = "133295606978042035",
                            PriceValue = 44.55f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("39854d4b-0330-49d4-a68a-c61cf95b98c0"),
                            LastUpdate = "133295606978042054",
                            PriceValue = 37.74f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("010a4ab9-00e8-4ad4-8b46-4fda33f837d8"),
                            LastUpdate = "133295606978042070",
                            PriceValue = 50.84f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("d692ee60-2223-4eba-9686-b395c9bd12c3"),
                            LastUpdate = "133295606978042087",
                            PriceValue = 326.51f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("2172ae92-c4ca-4209-a839-60e1fef491f0"),
                            LastUpdate = "133295606978042138",
                            PriceValue = 3721.11f
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("77e81505-7edc-4399-b106-8a311563bb60"),
                            LastUpdate = "133295606978042156",
                            PriceValue = 5503.05f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("185e8adf-1d4d-4878-8e6b-2bb61ac7a708"),
                            LastUpdate = "133295606978042172",
                            PriceValue = 7568.5f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("b9d812e4-c53a-4f59-b629-1d0c2dbac95c"),
                            LastUpdate = "133295606978042191",
                            PriceValue = 64.33f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("1fb87dae-7d38-4c28-9724-2606351a617e"),
                            LastUpdate = "133295606978042207",
                            PriceValue = 54.49f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("b7fc25b3-274c-4855-a2f4-c87859ddc948"),
                            LastUpdate = "133295606978042226",
                            PriceValue = 73.41f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("58537486-ee0f-4272-9bf2-b323c646b120"),
                            LastUpdate = "133295606978042242",
                            PriceValue = 471.52f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("a4f280a1-f930-408a-bb15-c32cd74d601e"),
                            LastUpdate = "133295606978042258",
                            PriceValue = 5373.63f
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("b8f10ba1-3a74-4868-aefd-56adbf2de327"),
                            LastUpdate = "133295606978042274",
                            PriceValue = 7946.92f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("787666b2-b37a-4a1c-8482-3c80fabcbd28"),
                            LastUpdate = "133295606978042290",
                            PriceValue = 1953.75f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("364866df-6921-4754-a297-ce7080b72356"),
                            LastUpdate = "133295606978042306",
                            PriceValue = 16.61f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("01df1fc3-95c9-4e47-85f6-6c28de55ad7a"),
                            LastUpdate = "133295606978042324",
                            PriceValue = 14.07f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("0a66ca2a-e991-46ca-a018-57a7076cd3da"),
                            LastUpdate = "133295606978042339",
                            PriceValue = 18.95f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("fb76a2ca-3acd-43f3-b834-bf26cf9e1f83"),
                            LastUpdate = "133295606978042359",
                            PriceValue = 121.72f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("39b600fa-89c4-4be0-977b-39fe375a4e23"),
                            LastUpdate = "133295606978042375",
                            PriceValue = 1387.16f
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("45781bae-5507-4808-82f1-c61bf0356075"),
                            LastUpdate = "133295606978042391",
                            PriceValue = 2051.44f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("0bfc6803-9a80-440e-b2c3-8f19d739bf49"),
                            LastUpdate = "133295606978042407",
                            PriceValue = 6546.5f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("4423d091-9937-4b1c-ac68-1c15f335ae74"),
                            LastUpdate = "133295606978042425",
                            PriceValue = 55.65f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("598ce200-550a-4f95-9979-bcb571d6db09"),
                            LastUpdate = "133295606978042441",
                            PriceValue = 47.13f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("f59b2577-5430-49e7-9a99-92c3eb8b54f7"),
                            LastUpdate = "133295606978042457",
                            PriceValue = 63.5f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("dcd873fa-3b40-41b4-ac96-3e7ab02e50a1"),
                            LastUpdate = "133295606978042473",
                            PriceValue = 407.85f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("097cbda5-269d-47af-ad31-ba3f9d0538a1"),
                            LastUpdate = "133295606978042523",
                            PriceValue = 4648.01f
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("09761da3-45a0-4730-b422-7b403eab14cc"),
                            LastUpdate = "133295606978042541",
                            PriceValue = 6873.82f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("dca9a655-e490-4efd-b046-24e0460ba056"),
                            LastUpdate = "133295606978042558",
                            PriceValue = 4037f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("6f343a07-6dbb-435f-a43a-efd6ae4f6325"),
                            LastUpdate = "133295606978042574",
                            PriceValue = 34.31f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("23db1c04-11d6-455c-96f2-2f9fcf508b72"),
                            LastUpdate = "133295606978042590",
                            PriceValue = 29.07f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("21536de3-5514-41c4-b462-3947851c2169"),
                            LastUpdate = "133295606978042606",
                            PriceValue = 39.16f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("7c151516-abdd-40f4-b078-942ad7b2ccd5"),
                            LastUpdate = "133295606978042622",
                            PriceValue = 251.51f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("18fd9a48-4d2a-40c0-9bdc-1f1a9931976f"),
                            LastUpdate = "133295606978042638",
                            PriceValue = 2866.27f
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("36079cc4-cfde-41fe-aa90-9c7affcaff07"),
                            LastUpdate = "133295606978042656",
                            PriceValue = 4238.85f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("563eceb5-8293-413d-878b-ae36ce42d91f"),
                            LastUpdate = "133295606978042673",
                            PriceValue = 8614.5f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("d2370f3c-798e-4594-85b2-02b13a637345"),
                            LastUpdate = "133295606978042689",
                            PriceValue = 73.22f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("87426d7f-ef21-4795-8c5b-b5eda5dcf50a"),
                            LastUpdate = "133295606978042708",
                            PriceValue = 62.02f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("87b35b55-40fb-4124-8500-6fb9c36aafa1"),
                            LastUpdate = "133295606978042724",
                            PriceValue = 83.56f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("f1574dda-54d4-4578-8974-47cc25f07f81"),
                            LastUpdate = "133295606978042740",
                            PriceValue = 536.68f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("77f9630a-a78b-4fde-b71c-f7914a4a4fdd"),
                            LastUpdate = "133295606978042756",
                            PriceValue = 6116.29f
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("c17ab520-e39e-41a4-a462-f8878f2d0931"),
                            LastUpdate = "133295606978042772",
                            PriceValue = 9045.22f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("d85ee87b-2d65-4862-9538-e63225dc9658"),
                            LastUpdate = "133295606978042791",
                            PriceValue = 1386.5f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("3022df15-ebeb-4bdd-a455-e7d36720000a"),
                            LastUpdate = "133295606978042807",
                            PriceValue = 11.79f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("652d4c24-3180-4e31-ab13-e6e91f0aa93d"),
                            LastUpdate = "133295606978042823",
                            PriceValue = 9.98f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("c11cfa67-3f2e-4db4-86cb-c835fa1ff788"),
                            LastUpdate = "133295606978042839",
                            PriceValue = 13.45f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("8691b4a3-5cf1-404a-884c-9dcb7b970e37"),
                            LastUpdate = "133295606978042890",
                            PriceValue = 86.38f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("eed833cc-c23b-45d7-bcbc-5b5f3d31bf76"),
                            LastUpdate = "133295606978042907",
                            PriceValue = 984.41f
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("faf63647-a554-4777-9fe6-0698be5245af"),
                            LastUpdate = "133295606978042923",
                            PriceValue = 1455.82f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("3a5e5da5-291f-4969-b31c-03be43da34c5"),
                            LastUpdate = "133295606978042939",
                            PriceValue = 5970.5f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("a2842945-4bf9-4ed3-af65-6936dfe8e523"),
                            LastUpdate = "133295606978042958",
                            PriceValue = 50.75f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("d5780211-1587-4fad-929c-88a34216642a"),
                            LastUpdate = "133295606978042974",
                            PriceValue = 42.99f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("161d161a-ec34-4a55-9701-16289474eeff"),
                            LastUpdate = "133295606978042990",
                            PriceValue = 57.91f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("15abdd39-229e-4660-8dc1-e3045ae5981a"),
                            LastUpdate = "133295606978043006",
                            PriceValue = 371.96f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("39782261-9352-4795-80c2-47366fe00949"),
                            LastUpdate = "133295606978043023",
                            PriceValue = 4239.05f
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("db965054-dbdb-4d0d-95d3-f9dea29d5e25"),
                            LastUpdate = "133295606978043039",
                            PriceValue = 6269.02f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("278f6486-ab70-4d88-9338-d6db083484c0"),
                            LastUpdate = "133295606978043055",
                            PriceValue = 3177.25f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("ef617b3e-271d-43e5-bfbd-40e3ed34cd41"),
                            LastUpdate = "133295606978043071",
                            PriceValue = 27.01f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("e38b4f36-5c30-41f7-bc68-a9855cf732b9"),
                            LastUpdate = "133295606978043090",
                            PriceValue = 22.88f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("fde599d6-a835-452c-ad31-2fc3130f1790"),
                            LastUpdate = "133295606978043107",
                            PriceValue = 30.82f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("2032e3e6-4892-4f6f-b3d3-8c9c852182ba"),
                            LastUpdate = "133295606978043123",
                            PriceValue = 197.94f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("d23a0a3b-7cfe-4c71-b30f-4fd5c74a84dd"),
                            LastUpdate = "133295606978043139",
                            PriceValue = 2255.85f
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("66ab40e1-b1b5-4530-a9ce-9f31170ad2c6"),
                            LastUpdate = "133295606978043156",
                            PriceValue = 3336.11f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("ef897741-466e-489c-9d56-334230b0af41"),
                            LastUpdate = "133295606978043172",
                            PriceValue = 9264.75f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("6ea3a5c3-cf64-424b-93fd-c40bbca263c3"),
                            LastUpdate = "133295606978043189",
                            PriceValue = 78.75f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("92829b6c-6f46-445b-993e-9cb4b253e41a"),
                            LastUpdate = "133295606978043205",
                            PriceValue = 66.71f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("2b42fe2b-1530-4725-a73c-7aaed03928f0"),
                            LastUpdate = "133295606978043223",
                            PriceValue = 89.87f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("8190a995-b534-4753-b2c5-a3e86a20857e"),
                            LastUpdate = "133295606978043240",
                            PriceValue = 577.19f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("37337a81-6984-4053-bd31-75385b55f39c"),
                            LastUpdate = "133295606978043314",
                            PriceValue = 6577.97f
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("41ffc365-ebdd-4f17-802b-82399e04640e"),
                            LastUpdate = "133295606978043332",
                            PriceValue = 9727.99f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("07063319-2b93-4de7-8ec0-f7cc25b08d24"),
                            LastUpdate = "133295606978043348",
                            PriceValue = 7812f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("b29fcf48-a90c-4a9a-8d58-84bb19367656"),
                            LastUpdate = "133295606978043364",
                            PriceValue = 66.4f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("77f6d077-c691-46fe-87e2-3cbb7b6db4ae"),
                            LastUpdate = "133295606978043380",
                            PriceValue = 56.25f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("0c54f70b-c7f4-4c88-bacb-676b4cefd7ef"),
                            LastUpdate = "133295606978043397",
                            PriceValue = 75.78f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("afe5e1f3-ba65-4939-ab66-1df9b33614da"),
                            LastUpdate = "133295606978043415",
                            PriceValue = 486.69f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("30ef7e2c-3268-43f4-9081-5ce8cf11bc66"),
                            LastUpdate = "133295606978043432",
                            PriceValue = 5546.52f
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("b372687f-937d-45c8-a604-495ca6fbe58c"),
                            LastUpdate = "133295606978043448",
                            PriceValue = 8202.6f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 1,
                            Currency = "RSD",
                            GlobalId = new Guid("7a063f5f-cf2d-419f-b53b-24179e5c7ccd"),
                            LastUpdate = "133295606978043464",
                            PriceValue = 2985.25f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 2,
                            Currency = "EUR",
                            GlobalId = new Guid("fd96ec09-10dd-4e5e-a23c-e4fab1a60ccc"),
                            LastUpdate = "133295606978043480",
                            PriceValue = 25.37f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 3,
                            Currency = "GBP",
                            GlobalId = new Guid("66115dbf-033f-49bb-9127-e5b36dfa0230"),
                            LastUpdate = "133295606978043497",
                            PriceValue = 21.49f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 4,
                            Currency = "USD",
                            GlobalId = new Guid("10901642-4a5a-460f-bb11-adc1f6bf083d"),
                            LastUpdate = "133295606978043513",
                            PriceValue = 28.96f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 5,
                            Currency = "RMB",
                            GlobalId = new Guid("9b7a3351-5452-4959-931b-f2c8d81f40d6"),
                            LastUpdate = "133295606978043529",
                            PriceValue = 185.98f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 6,
                            Currency = "INR",
                            GlobalId = new Guid("17a9d986-b85d-4d07-8719-5cda4e5ab2db"),
                            LastUpdate = "133295606978043548",
                            PriceValue = 2119.53f
                        },
                        new
                        {
                            ProductId = 16,
                            PriceListId = 7,
                            Currency = "JPY",
                            GlobalId = new Guid("6957370e-8b3a-4a69-9149-fa9864872259"),
                            LastUpdate = "133295606978043564",
                            PriceValue = 3134.51f
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a43db411"),
                            LastUpdate = "634792557112051690",
                            Name = "RSD Price List"
                        },
                        new
                        {
                            Id = 2,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a13db412"),
                            LastUpdate = "634792557112051691",
                            Name = "EUR Price List"
                        },
                        new
                        {
                            Id = 3,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db413"),
                            LastUpdate = "634792557112051692",
                            Name = "GBP Price List"
                        },
                        new
                        {
                            Id = 4,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a43db414"),
                            LastUpdate = "634792557112051693",
                            Name = "USD Price List"
                        },
                        new
                        {
                            Id = 5,
                            GlobalId = new Guid("494ad824-8ee2-47c3-938f-2de7a13db415"),
                            LastUpdate = "634792557112051694",
                            Name = "RMB Price List"
                        },
                        new
                        {
                            Id = 6,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db416"),
                            LastUpdate = "634792557112051695",
                            Name = "INR Price List"
                        },
                        new
                        {
                            Id = 7,
                            GlobalId = new Guid("494b7014-8ee2-47c3-938f-2de7a43db41a"),
                            LastUpdate = "634792557112051696",
                            Name = "JPY Price List"
                        },
                        new
                        {
                            Id = 8,
                            GlobalId = new Guid("16cabf28-d1ae-4dc4-adb3-a047e10cd113"),
                            LastUpdate = "634792557112051697",
                            Name = "RSD 2 Price List"
                        },
                        new
                        {
                            Id = 9,
                            GlobalId = new Guid("dbaf7a71-4b18-40bd-a720-a515817cc468"),
                            LastUpdate = "634792557112051698",
                            Name = "EUR 2 Price List"
                        },
                        new
                        {
                            Id = 10,
                            GlobalId = new Guid("dd67964e-3b02-4e86-95d3-9d16485bbb8f"),
                            LastUpdate = "634792557112051699",
                            Name = "GBP 2 Price List"
                        },
                        new
                        {
                            Id = 11,
                            GlobalId = new Guid("1b132289-f817-4d98-8f21-3691617054e0"),
                            LastUpdate = "634792557112051701",
                            Name = "USD 2 Price List"
                        },
                        new
                        {
                            Id = 12,
                            GlobalId = new Guid("481a7110-98ee-471b-9646-a781f9fcadb6"),
                            LastUpdate = "634792557112051702",
                            Name = "RMB 2 Price List"
                        },
                        new
                        {
                            Id = 13,
                            GlobalId = new Guid("f98bd15f-f7d3-4522-866e-cc57ad3c5d38"),
                            LastUpdate = "634792557112051703",
                            Name = "INR 2 Price List"
                        },
                        new
                        {
                            Id = 14,
                            GlobalId = new Guid("b6718658-f490-4357-82ea-40acf1fd5259"),
                            LastUpdate = "634792557112051704",
                            Name = "JPY 2 Price List"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 104,
                            GlobalId = new Guid("6f68f25e-9645-4da9-b66f-8edbebb8a6e7"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mbO0YJ-ovSlqOuXjgGPR2IsjN8sCk9ULksyzIkvLEJeRyYnqKUxHmuxppx-HMcp6oNzzOrMc6_6YRgmiaeA5_vxCRWCV9ARd_GK6hPLdp3tEcsgR7Us9uzAfvH331KiJrqlwCGiOPFDi_OsHLznB3tqbTk-bFfQIqQdyTkno03JxvSOQ8vwEjvCFJUa0Bx7IUBzg4bU_qzf3qpgZMeYI1y1rt9qCldOaIi3WgyU-E5J0?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBlack"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 138,
                            GlobalId = new Guid("d68bce12-9f03-4e5f-b0b9-3ad1205afda4"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4m-kRT2GTNRM1fORXdHbHlvpzF8ne8_HsD3AoL-ytcD5vCq2S7olsPp-Nnw017SkIRz6yUxkIym7En4FjUFiENJ2BVJN0TWz9aqDHht8mlh5RrTwQ-ZBXD6Lm8fI9cy390BzcPCGZchRsm6dGkmTU3q3xZE-WU1VNKV-64xUJN02ofGt6w7I7vJxqaeaHh15q_ul04x3dCUumC53DWniI5oEilVornGdGyddxKc8xZoqw?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBlue"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 745,
                            GlobalId = new Guid("2c103912-7b0f-4469-8769-3989a4d62bc2"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mAsciDm3-1F9piIJKD-IzaefrUBqEbA6CPHpORsvcIBh6PK8Ze9TOhMEvKpBx0RhBUTOIP5AItxqcmLSMiYSz2g7KV8XG0jugLvNtkqC8R1DwnwOQRZHj3csgnd_iTL1qWPfzolxTny7naR0izqMtG3i-w3ziMWHQuEqzwiTc98QTHj8LfkRuMHhv72ZNttAQuoj3-Y2iHokZ4JsuU5DkNfzVpvAKZ4w5wgS5V99rOD8?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBrown"
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 5,
                            GlobalId = new Guid("a6c74b0b-b1f3-4e12-b6d2-6c38a3903ce6"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mIMtsMKg4MteMPQCPtJgs6K1S-d2um3XXpYS8Du6_NWnd4lNDiHdlq6Eb524q2jskw_8_vshuYV5u-K6AO8mxW2llKQxnBEL01m5t-JNBM5LecnrYtGho2DiJipC6x4r3jD1VeW34xPSR1p_juV-1oqWdrrQUf8PbaDdD75jE3ar1KeD9yUlPhM5BUrCTjzaJusBxqVk0smMVMzQ7Bja62BV6-4jQ0W743Q1JiUNeOPA?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtGreen"
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 57,
                            GlobalId = new Guid("8dbff2d4-42a0-4fe7-9864-05571f3c22db"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4m0eG0CddqsLAfGnFHIiySLlbn9TzPQ9pQOm7YcP9QXblbZJauurhybDbiJTbA4xb-obY2cjRUlaacpZakO8zQ1oDTZQrDaipf0vU9FiylYlxK64_CzrAuGrJenGE98iclH6BN9uWZH3k1V5XthDTzldVwtY2lvP_upoU-UQyNGfX0goTCeF3FnK7rHh5pwIPSQWwSeHNPserQ6skA9FWR0ehISp1axZbphMw6aYmQwhU?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtPurple"
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 224,
                            GlobalId = new Guid("9f7c8b37-0e37-49ed-af1f-4e6a7428a873"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mLQ8P5MJROOmihR3K_1SU4Y_Iisgc0y1DeC-ZizOELnj82YZeiGhXEY8cavf9xNTC12wtRKmUN42mQysBXyV066A8XFzE9XNScQNdflZhIhCKM0xUmgKHlCG6P9z3jIiqdxENbwxFU6dBr1UEpJpaZXWRHliG8nJNI1TttSsDw533HGJR5gCO9hpdlDDz4W0ltkmYE_oPT24JKDwnLNZyHZv6dfzI-qqzOrlBa5TnPQQ?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtRed"
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 150,
                            GlobalId = new Guid("e0a01813-5f43-4a15-934f-9946ef8f4182"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4m0BTJrLTQNPzne4u5bX6n47paz88nldiOZnxawfhv4oJKFk8fP4TZR91HGDs43pSIw2wEXKbJq3cJ8pItmZ-tu9LSPBEpjbTo5jIuiMsFipvDwkZoT4r9C0DHCYD6vVjnRdGP0OgbxKBKGgtOXUlc3hMb3KalQVb5xlK1EC_ukMs5cLmBeHqGzEmI2SBe3zCyeoNgaf3GpysUv9NAcoG1ppL0FCXfJMJbM0zWUbcSfJ0?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtRose"
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 186,
                            GlobalId = new Guid("156fd903-9fd2-41af-9b09-600d598b31c4"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4m8PzFIhNEKewi3wbogTAR2veLJqFbaOBgSNlzytwuowu0Lv2SIQxwPhsPe9EFmuc0N8lgEdowWmm29Cavcz6isxa4cpPVOr6jtl9BW5Ajv4lcvKSE4oXqNIMeElwiw53q6Bg84U_VG1c3ntS0UCXSMdo4iRDZJURcBbeIDv7GFCnRKcgMHQ6FD1md_owl3q55SGzBIEsFOpyMku_CcvDb77ttqpDhJ4YPF9CCbzQ8esk?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtYellow"
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 104,
                            GlobalId = new Guid("6f8799a7-097b-45f4-a8f0-805784ee24a6"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mcROrUsGJ1C_DaPGGRsunJPAdSjzSLWBSqcDa4cHQt2VRY9AZqbHg4T7EPdSV1btrGwXH7VAJuf61Ld1knMXgnsRqdUuLpQkQCtWFYohlEv9VAK3QZzHC6XaVQNugbmcDj03yOM09WghkBH2eDm_EV5MF8iXSjIOwAktBC9Qet-CY16VN2MSm7UFFgw94gEbasO_GBbkRvzfCwOmUcXICRMopHO6obWAB_ATRGjlLHO4?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBlack 9 Gradient"
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 138,
                            GlobalId = new Guid("49674251-6b45-437f-8c7a-34a0b1a34c01"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4myPaEj8lwOAp9D6FSSd6vqVOshe2DZNPeTkOqpYexCSHAtxzO73MHXGGEkScMtu8k1iYqm2lKRBn5DMz5f0zerCAOvzrd8pGwL_fmarBVTMSmopv0Vy1YV5FDpu1-hPgVG0zKhYbu0jy8x2n4_ZOpZTDjzcrwrJrE78DuISNhBLvF2SGidifBduSxqFfXd7DPF_2Gr4dIMcymuT-OBT2opZWcpARi9ccxq-vfz-KPnqA?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBlue 9 Gradient"
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 745,
                            GlobalId = new Guid("7b5ae8b9-12a0-4a19-9c37-943bc4cc5a3e"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4maMJZDwT_Bt_9lYoj4QEBJplPpSpox0xs8mlm5MJZp-e4mC1TTol3ATfgm9TGwDlCcYnXzdhSqaPeqkZJK90tgRR_KQHtctku28zVSo3D8Rf_462QClZiF4CC03XosaZsn0ZWDdq7KhWdYpC8hUpkJQf9bbvjeRgYJfdHr8yqhGO3ENu8lAwvwUIMRs9LaXDIBAaXurelBc7zK18wxVt8opgjC4MvmdhJC0rjqWefNk8?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtBrown 9 Gradient"
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 5,
                            GlobalId = new Guid("097dbb41-2aa0-4fbf-8986-bdf8e4e0d4b9"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mywnSFEOeNPAc3Dv5LG3QKmt8cnkjDcCHmNyhpMMvkFiSJlUvZkss9mSJAYld9eYyTO4ELiz4sMXc2pgLtrqqsjzrTfWHItrt9Vesn1xHDXi7ONiXvdldHGHQwBDoTr5yQhbvShlKJVTfpL0UM67KIKTjDH3c9MqAUc2S8bwTjmai-g_WeOH4BdyJZz41mDWGTS88odSwCfN94gatrXq-Nc4vr96zUOhvoWSJHQPm-rE?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtGreen 9 Gradient"
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 57,
                            GlobalId = new Guid("5f8d15b2-4c4d-4e7a-8902-d78d3b4cb10b"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mkHeVXwv9fF7d7rmBK_fJ0Ge3c07dLoVpzqCrrF5HIEFDpKXFGkoRnJ9WmXzt1-bsSG3J5gSP8C3Aj5p8GjTS_tnZrGMCj2oNJbYvMRbyJbAzA3Gy7ynLFEdddnq8cNHwwWB4Jh2k8988ufJ7H-p2oe5lr4oQRvshHBzuIRt52RNWaGspRAVow1L551awcDC_BfmD2se_Yg9guDVlDTOMqVvO9PEqlMP3B-3y_I9oIz0?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtPurple 9 Gradient"
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 224,
                            GlobalId = new Guid("4d50363a-2dc4-4ef0-8bde-682758f0f801"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mAuqUBcOB4e_6Pkv5WtCBhsOp6xQyB3dhrzYEuJsoMAijFJ6pSGth6esbBkAIU2JpgSDze6vTEC07JiJWAPnyjuL2PsE_bmP1XypvPO3HZP2uIDAThpD-nk4Ews_QeQd0TNNorcNqO6JqaEqIP9OpEEfkLnBcK5Q0FHBI3IxP6octHzAlY5_M-z93ypRdrhwBjEjnmpEBsZ7eeZwORwXxRa1nw2b-TwPSr6F6uZZ2MUs?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtRed 9 Gradient"
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 150,
                            GlobalId = new Guid("1835ee0e-3275-4ff9-9d79-1a2e3b5e15e3"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4mUU4G3Dpx9xkjqniNIZeMWz-wr3t18PGCtpoQxOv522aU8IDNVk6-MWFtqONztKzH6BelSIR6NhOXklxW5CEhTct5nyscvSGwHujoHepodUBhtjuXXW2KudArDxA2g4ARoELCaWVCAvdAm46C7BnzDcbXRf4QBFvz-iUG9V-Nm7O1adpQ6gnF96Xkp2iyNrkGkpc0x2hJ06TVqNWDYM7XfrJooKEbFfYcllC7cy17X5E?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtRose 9 Gradient"
                        },
                        new
                        {
                            Id = 16,
                            AvailableQuantity = 186,
                            GlobalId = new Guid("e5e4a551-2b64-43fc-86e1-4c1c0f6880fe"),
                            ImageUrl = "https://db3pap003files.storage.live.com/y4m9Oo0CoS06pvC58i8iE_2_WfJE-rEuIMGRWZcbdjThze0gTjJBWWtaDGSsnxJmhCweSY3lvNc6ZYxLMV8zlKM5CTJ24-WbT4iLjCtOgYg_Oy3hxxhcZOTXkMefthHQhT2OxtSmUDKkQIf4shsWTIu81eHGEovGq63_UqM-gkXR0uqYZXZLfgmVR9cTgk4Hyt8dmweIrouQ_eGM4L7TS5xP3d74G3moTJ72Lzjv8XLbSo?encodeFailures=1&width=500&height=500",
                            LastUpdate = "111111111111111111",
                            Name = "T-ShirtYellow 9 Gradient"
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.ProductDocument", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<float>("PriceValue")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ProductDocuments");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DocumentId = 1,
                            Currency = "USD",
                            PriceValue = 12f,
                            Quantity = 11
                        });
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Client", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Price", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.PriceList", "PriceList")
                        .WithMany("Prices")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.ERP.Domain.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.ProductDocument", b =>
                {
                    b.HasOne("Levi9.ERP.Domain.Models.Document", "Document")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Levi9.ERP.Domain.Models.Product", "Product")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Document", b =>
                {
                    b.Navigation("ProductDocuments");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.PriceList", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Levi9.ERP.Domain.Models.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
